// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgolog

import (
	"context"

	"github.com/jkaveri/golog/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewWriter creates a new instance of Writer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Writer {
	mock := &Writer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Writer is an autogenerated mock type for the Writer type
type Writer struct {
	mock.Mock
}

type Writer_Expecter struct {
	mock *mock.Mock
}

func (_m *Writer) EXPECT() *Writer_Expecter {
	return &Writer_Expecter{mock: &_m.Mock}
}

// Write provides a mock function for the type Writer
func (_mock *Writer) Write(ctx context.Context, record golog.Record) error {
	ret := _mock.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, golog.Record) error); ok {
		r0 = returnFunc(ctx, record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Writer_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type Writer_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - record golog.Record
func (_e *Writer_Expecter) Write(ctx interface{}, record interface{}) *Writer_Write_Call {
	return &Writer_Write_Call{Call: _e.mock.On("Write", ctx, record)}
}

func (_c *Writer_Write_Call) Run(run func(ctx context.Context, record golog.Record)) *Writer_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 golog.Record
		if args[1] != nil {
			arg1 = args[1].(golog.Record)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Writer_Write_Call) Return(err error) *Writer_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Writer_Write_Call) RunAndReturn(run func(ctx context.Context, record golog.Record) error) *Writer_Write_Call {
	_c.Call.Return(run)
	return _c
}
