// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgolog

import (
	"context"

	"github.com/jkaveri/golog/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

type Logger_Expecter struct {
	mock *mock.Mock
}

func (_m *Logger) EXPECT() *Logger_Expecter {
	return &Logger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type Logger
func (_mock *Logger) Debug(msg string, args ...golog.Attr) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// Logger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type Logger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - args ...golog.Attr
func (_e *Logger_Expecter) Debug(msg interface{}, args ...interface{}) *Logger_Debug_Call {
	return &Logger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{msg}, args...)...)}
}

func (_c *Logger_Debug_Call) Run(run func(msg string, args ...golog.Attr)) *Logger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []golog.Attr
		var variadicArgs []golog.Attr
		if len(args) > 1 {
			variadicArgs = args[1].([]golog.Attr)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Logger_Debug_Call) Return() *Logger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_Debug_Call) RunAndReturn(run func(msg string, args ...golog.Attr)) *Logger_Debug_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type Logger
func (_mock *Logger) Error(msg string, args ...golog.Attr) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// Logger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type Logger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - args ...golog.Attr
func (_e *Logger_Expecter) Error(msg interface{}, args ...interface{}) *Logger_Error_Call {
	return &Logger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{msg}, args...)...)}
}

func (_c *Logger_Error_Call) Run(run func(msg string, args ...golog.Attr)) *Logger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []golog.Attr
		var variadicArgs []golog.Attr
		if len(args) > 1 {
			variadicArgs = args[1].([]golog.Attr)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Logger_Error_Call) Return() *Logger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_Error_Call) RunAndReturn(run func(msg string, args ...golog.Attr)) *Logger_Error_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type Logger
func (_mock *Logger) Info(msg string, args ...golog.Attr) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// Logger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type Logger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - args ...golog.Attr
func (_e *Logger_Expecter) Info(msg interface{}, args ...interface{}) *Logger_Info_Call {
	return &Logger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{msg}, args...)...)}
}

func (_c *Logger_Info_Call) Run(run func(msg string, args ...golog.Attr)) *Logger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []golog.Attr
		var variadicArgs []golog.Attr
		if len(args) > 1 {
			variadicArgs = args[1].([]golog.Attr)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Logger_Info_Call) Return() *Logger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_Info_Call) RunAndReturn(run func(msg string, args ...golog.Attr)) *Logger_Info_Call {
	_c.Run(run)
	return _c
}

// SetLevel provides a mock function for the type Logger
func (_mock *Logger) SetLevel(level golog.Level) {
	_mock.Called(level)
	return
}

// Logger_SetLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLevel'
type Logger_SetLevel_Call struct {
	*mock.Call
}

// SetLevel is a helper method to define mock.On call
//   - level golog.Level
func (_e *Logger_Expecter) SetLevel(level interface{}) *Logger_SetLevel_Call {
	return &Logger_SetLevel_Call{Call: _e.mock.On("SetLevel", level)}
}

func (_c *Logger_SetLevel_Call) Run(run func(level golog.Level)) *Logger_SetLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 golog.Level
		if args[0] != nil {
			arg0 = args[0].(golog.Level)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Logger_SetLevel_Call) Return() *Logger_SetLevel_Call {
	_c.Call.Return()
	return _c
}

func (_c *Logger_SetLevel_Call) RunAndReturn(run func(level golog.Level)) *Logger_SetLevel_Call {
	_c.Run(run)
	return _c
}

// With provides a mock function for the type Logger
func (_mock *Logger) With(args ...golog.Attr) golog.Logger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for With")
	}

	var r0 golog.Logger
	if returnFunc, ok := ret.Get(0).(func(...golog.Attr) golog.Logger); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(golog.Logger)
		}
	}
	return r0
}

// Logger_With_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'With'
type Logger_With_Call struct {
	*mock.Call
}

// With is a helper method to define mock.On call
//   - args ...golog.Attr
func (_e *Logger_Expecter) With(args ...interface{}) *Logger_With_Call {
	return &Logger_With_Call{Call: _e.mock.On("With",
		append([]interface{}{}, args...)...)}
}

func (_c *Logger_With_Call) Run(run func(args ...golog.Attr)) *Logger_With_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []golog.Attr
		var variadicArgs []golog.Attr
		if len(args) > 0 {
			variadicArgs = args[0].([]golog.Attr)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Logger_With_Call) Return(logger golog.Logger) *Logger_With_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *Logger_With_Call) RunAndReturn(run func(args ...golog.Attr) golog.Logger) *Logger_With_Call {
	_c.Call.Return(run)
	return _c
}

// WithContext provides a mock function for the type Logger
func (_mock *Logger) WithContext(ctx context.Context) golog.Logger {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WithContext")
	}

	var r0 golog.Logger
	if returnFunc, ok := ret.Get(0).(func(context.Context) golog.Logger); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(golog.Logger)
		}
	}
	return r0
}

// Logger_WithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithContext'
type Logger_WithContext_Call struct {
	*mock.Call
}

// WithContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Logger_Expecter) WithContext(ctx interface{}) *Logger_WithContext_Call {
	return &Logger_WithContext_Call{Call: _e.mock.On("WithContext", ctx)}
}

func (_c *Logger_WithContext_Call) Run(run func(ctx context.Context)) *Logger_WithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Logger_WithContext_Call) Return(logger golog.Logger) *Logger_WithContext_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *Logger_WithContext_Call) RunAndReturn(run func(ctx context.Context) golog.Logger) *Logger_WithContext_Call {
	_c.Call.Return(run)
	return _c
}

// WithError provides a mock function for the type Logger
func (_mock *Logger) WithError(err error) golog.Logger {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for WithError")
	}

	var r0 golog.Logger
	if returnFunc, ok := ret.Get(0).(func(error) golog.Logger); ok {
		r0 = returnFunc(err)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(golog.Logger)
		}
	}
	return r0
}

// Logger_WithError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithError'
type Logger_WithError_Call struct {
	*mock.Call
}

// WithError is a helper method to define mock.On call
//   - err error
func (_e *Logger_Expecter) WithError(err interface{}) *Logger_WithError_Call {
	return &Logger_WithError_Call{Call: _e.mock.On("WithError", err)}
}

func (_c *Logger_WithError_Call) Run(run func(err error)) *Logger_WithError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Logger_WithError_Call) Return(logger golog.Logger) *Logger_WithError_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *Logger_WithError_Call) RunAndReturn(run func(err error) golog.Logger) *Logger_WithError_Call {
	_c.Call.Return(run)
	return _c
}
