// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockgolog

import (
	"context"

	"github.com/jkaveri/golog/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewEnricher creates a new instance of Enricher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEnricher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Enricher {
	mock := &Enricher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Enricher is an autogenerated mock type for the Enricher type
type Enricher struct {
	mock.Mock
}

type Enricher_Expecter struct {
	mock *mock.Mock
}

func (_m *Enricher) EXPECT() *Enricher_Expecter {
	return &Enricher_Expecter{mock: &_m.Mock}
}

// Enrich provides a mock function for the type Enricher
func (_mock *Enricher) Enrich(ctx context.Context, builder *golog.RecordBuilder) {
	_mock.Called(ctx, builder)
	return
}

// Enricher_Enrich_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enrich'
type Enricher_Enrich_Call struct {
	*mock.Call
}

// Enrich is a helper method to define mock.On call
//   - ctx context.Context
//   - builder *golog.RecordBuilder
func (_e *Enricher_Expecter) Enrich(ctx interface{}, builder interface{}) *Enricher_Enrich_Call {
	return &Enricher_Enrich_Call{Call: _e.mock.On("Enrich", ctx, builder)}
}

func (_c *Enricher_Enrich_Call) Run(run func(ctx context.Context, builder *golog.RecordBuilder)) *Enricher_Enrich_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *golog.RecordBuilder
		if args[1] != nil {
			arg1 = args[1].(*golog.RecordBuilder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Enricher_Enrich_Call) Return() *Enricher_Enrich_Call {
	_c.Call.Return()
	return _c
}

func (_c *Enricher_Enrich_Call) RunAndReturn(run func(ctx context.Context, builder *golog.RecordBuilder)) *Enricher_Enrich_Call {
	_c.Run(run)
	return _c
}
