// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package golog

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockWriter creates a new instance of MockWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriter {
	mock := &MockWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

type MockWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriter) EXPECT() *MockWriter_Expecter {
	return &MockWriter_Expecter{mock: &_m.Mock}
}

// Write provides a mock function for the type MockWriter
func (_mock *MockWriter) Write(ctx context.Context, record Record) error {
	ret := _mock.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Record) error); ok {
		r0 = returnFunc(ctx, record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - record Record
func (_e *MockWriter_Expecter) Write(ctx interface{}, record interface{}) *MockWriter_Write_Call {
	return &MockWriter_Write_Call{Call: _e.mock.On("Write", ctx, record)}
}

func (_c *MockWriter_Write_Call) Run(run func(ctx context.Context, record Record)) *MockWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Record
		if args[1] != nil {
			arg1 = args[1].(Record)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWriter_Write_Call) Return(err error) *MockWriter_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWriter_Write_Call) RunAndReturn(run func(ctx context.Context, record Record) error) *MockWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}
