// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package golog

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type MockLogger
func (_mock *MockLogger) Debug(msg string, args ...Attr) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - args ...Attr
func (_e *MockLogger_Expecter) Debug(msg interface{}, args ...interface{}) *MockLogger_Debug_Call {
	return &MockLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockLogger_Debug_Call) Run(run func(msg string, args ...Attr)) *MockLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []Attr
		var variadicArgs []Attr
		if len(args) > 1 {
			variadicArgs = args[1].([]Attr)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Debug_Call) Return() *MockLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debug_Call) RunAndReturn(run func(msg string, args ...Attr)) *MockLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MockLogger
func (_mock *MockLogger) Error(msg string, args ...Attr) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - args ...Attr
func (_e *MockLogger_Expecter) Error(msg interface{}, args ...interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(msg string, args ...Attr)) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []Attr
		var variadicArgs []Attr
		if len(args) > 1 {
			variadicArgs = args[1].([]Attr)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(msg string, args ...Attr)) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type MockLogger
func (_mock *MockLogger) Info(msg string, args ...Attr) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - args ...Attr
func (_e *MockLogger_Expecter) Info(msg interface{}, args ...interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(msg string, args ...Attr)) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []Attr
		var variadicArgs []Attr
		if len(args) > 1 {
			variadicArgs = args[1].([]Attr)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(msg string, args ...Attr)) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// SetLevel provides a mock function for the type MockLogger
func (_mock *MockLogger) SetLevel(level Level) {
	_mock.Called(level)
	return
}

// MockLogger_SetLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLevel'
type MockLogger_SetLevel_Call struct {
	*mock.Call
}

// SetLevel is a helper method to define mock.On call
//   - level Level
func (_e *MockLogger_Expecter) SetLevel(level interface{}) *MockLogger_SetLevel_Call {
	return &MockLogger_SetLevel_Call{Call: _e.mock.On("SetLevel", level)}
}

func (_c *MockLogger_SetLevel_Call) Run(run func(level Level)) *MockLogger_SetLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Level
		if args[0] != nil {
			arg0 = args[0].(Level)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogger_SetLevel_Call) Return() *MockLogger_SetLevel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_SetLevel_Call) RunAndReturn(run func(level Level)) *MockLogger_SetLevel_Call {
	_c.Run(run)
	return _c
}

// With provides a mock function for the type MockLogger
func (_mock *MockLogger) With(args ...Attr) Logger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for With")
	}

	var r0 Logger
	if returnFunc, ok := ret.Get(0).(func(...Attr) Logger); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Logger)
		}
	}
	return r0
}

// MockLogger_With_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'With'
type MockLogger_With_Call struct {
	*mock.Call
}

// With is a helper method to define mock.On call
//   - args ...Attr
func (_e *MockLogger_Expecter) With(args ...interface{}) *MockLogger_With_Call {
	return &MockLogger_With_Call{Call: _e.mock.On("With",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_With_Call) Run(run func(args ...Attr)) *MockLogger_With_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []Attr
		var variadicArgs []Attr
		if len(args) > 0 {
			variadicArgs = args[0].([]Attr)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockLogger_With_Call) Return(logger Logger) *MockLogger_With_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockLogger_With_Call) RunAndReturn(run func(args ...Attr) Logger) *MockLogger_With_Call {
	_c.Call.Return(run)
	return _c
}

// WithContext provides a mock function for the type MockLogger
func (_mock *MockLogger) WithContext(ctx context.Context) Logger {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WithContext")
	}

	var r0 Logger
	if returnFunc, ok := ret.Get(0).(func(context.Context) Logger); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Logger)
		}
	}
	return r0
}

// MockLogger_WithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithContext'
type MockLogger_WithContext_Call struct {
	*mock.Call
}

// WithContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLogger_Expecter) WithContext(ctx interface{}) *MockLogger_WithContext_Call {
	return &MockLogger_WithContext_Call{Call: _e.mock.On("WithContext", ctx)}
}

func (_c *MockLogger_WithContext_Call) Run(run func(ctx context.Context)) *MockLogger_WithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogger_WithContext_Call) Return(logger Logger) *MockLogger_WithContext_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockLogger_WithContext_Call) RunAndReturn(run func(ctx context.Context) Logger) *MockLogger_WithContext_Call {
	_c.Call.Return(run)
	return _c
}

// WithError provides a mock function for the type MockLogger
func (_mock *MockLogger) WithError(err error) Logger {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for WithError")
	}

	var r0 Logger
	if returnFunc, ok := ret.Get(0).(func(error) Logger); ok {
		r0 = returnFunc(err)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Logger)
		}
	}
	return r0
}

// MockLogger_WithError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithError'
type MockLogger_WithError_Call struct {
	*mock.Call
}

// WithError is a helper method to define mock.On call
//   - err error
func (_e *MockLogger_Expecter) WithError(err interface{}) *MockLogger_WithError_Call {
	return &MockLogger_WithError_Call{Call: _e.mock.On("WithError", err)}
}

func (_c *MockLogger_WithError_Call) Run(run func(err error)) *MockLogger_WithError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogger_WithError_Call) Return(logger Logger) *MockLogger_WithError_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockLogger_WithError_Call) RunAndReturn(run func(err error) Logger) *MockLogger_WithError_Call {
	_c.Call.Return(run)
	return _c
}
