// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package golog

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEnricher creates a new instance of MockEnricher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnricher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnricher {
	mock := &MockEnricher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEnricher is an autogenerated mock type for the Enricher type
type MockEnricher struct {
	mock.Mock
}

type MockEnricher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnricher) EXPECT() *MockEnricher_Expecter {
	return &MockEnricher_Expecter{mock: &_m.Mock}
}

// Enrich provides a mock function for the type MockEnricher
func (_mock *MockEnricher) Enrich(ctx context.Context, builder *RecordBuilder) {
	_mock.Called(ctx, builder)
	return
}

// MockEnricher_Enrich_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enrich'
type MockEnricher_Enrich_Call struct {
	*mock.Call
}

// Enrich is a helper method to define mock.On call
//   - ctx context.Context
//   - builder *RecordBuilder
func (_e *MockEnricher_Expecter) Enrich(ctx interface{}, builder interface{}) *MockEnricher_Enrich_Call {
	return &MockEnricher_Enrich_Call{Call: _e.mock.On("Enrich", ctx, builder)}
}

func (_c *MockEnricher_Enrich_Call) Run(run func(ctx context.Context, builder *RecordBuilder)) *MockEnricher_Enrich_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *RecordBuilder
		if args[1] != nil {
			arg1 = args[1].(*RecordBuilder)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEnricher_Enrich_Call) Return() *MockEnricher_Enrich_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEnricher_Enrich_Call) RunAndReturn(run func(ctx context.Context, builder *RecordBuilder)) *MockEnricher_Enrich_Call {
	_c.Run(run)
	return _c
}
